[package]
name = "sulphire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"
wait-timeout = "0.2.0"
fancy-regex = "0.8.0"